### ISSUE TITLE
UploadBox iframe is not correctly arranged

### ISSUE THREAD

**Issue by MaStr** [PirateBox-Dev/PirateBoxScripts_Webserver#126]
The content from droopy is looking quite messy 
![screenshot_2015-09-30_03-34-11](https://cloud.githubusercontent.com/assets/1036501/10182410/24c8b054-6724-11e5-9072-a9eace5a2abb.png)

Should be better centered. Maybe droopy adjustments are needed.

**Comment by deavmi** [comment]
Yeah. I have seen this. Keep up the good work.
