### ISSUE TITLE
delete_empty.sh will attempt to delete files in filesystem if directory does not exist

### ISSUE THREAD

**Issue by yamatt** [PirateBox-Dev/PirateBoxScripts_Webserver#133]
Had a play with piratebox last night and found that if your uploads directory does not exist and you stop the service that `delete-empty.sh` will try to `cd` to that directory, fail, then continue with the rest of the script and delete all 0 byte files from `/`. This includes configuration files in `/etc` and other places.

It would be useful to check if either the `cd` worked, or that the directory to `cd` to existed before continuing with the script.

**Comment by MaStr** [comment]
Thanks for pointing this out. I just fixed it. It will be released in the 1.0.7 version!

**Comment by yamatt** [comment]
@MaStr Great work. Thanks :)
