### ISSUE TITLE
starting miniircd in development build for OpenWRT (CC/Zsun)

### ISSUE THREAD

**Issue by TheExpertNoob** [PirateBox-Dev/PirateBoxScripts_Webserver#150]
Starting Miniircd...
start-stop-daemon: unrecognized option `--exec'
BusyBox v1.23.2 (2016-01-07 20:06:15 CET) multi-call binary.

~truncated~
1

**Comment by TheExpertNoob** [comment]
should be?
start IRC
start-stop-daemon $DROOPY_USER -m -S -p $PIDFILE_IRC -x $PIRATEBOX/bin/miniircd.py -- $IRC_PARMS
stop IRC
start-stop-daemon -K -q -p $PIDFILE_IRC

also make a note of how to list channels in MOTD /raw LIST

**Comment by MaStr** [comment]
Good catch! 
Can you make a pull request?

**Comment by TheExpertNoob** [comment]
Fixed
