### ISSUE TITLE
Add sb_style.css to python_lib/psogen.py

### ISSUE THREAD

**Issue by MaStr** [PirateBox-Dev/PirateBoxScripts_Webserver#176]
To enable easier customization of shoutbox

**Comment by stylesuxx** [comment]
Am 20.07.2017 16:52 schrieb "Matthias Strubel" <notifications@github.com>:

**Comment by MaStr** [comment]
Needs to be double checked, because theoretical, the stylesheet of the parent page (index.html) is in place. So it might be sufficient to add an id tag to the corresponding html tag.
The original request was to make the background configurable.

**Comment by MaStr** [comment]
was a false report
