### ISSUE TITLE
development-tree ; python shoutbox not working anymore

### ISSUE THREAD

**Issue by MaStr** [PirateBox-Dev/PirateBoxScripts_Webserver#97]
It seem the line

```python
content = "<div class='message'><date>{0}</date> <name>{1}:</name>" \
"<data class='{2}'>{3}</data></div>\n"
content.format(curdate.strftime("%H:%M:%S"), name, color, data)
```

does not work on openwrt. The soutbox generates 

> {0} {1}:{3}

as output

**Comment by Liblor** [comment]
I'll have a look at it. I only tried it with the python interpreter (on openwrt) and it worked...

Right now I'm not running the dev-version, I'll upgrade and check it.

**Comment by MaStr** [comment]
works again
